// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repositories

import (
	"database/sql"
)

type GooseDbVersion struct {
	ID        int64
	VersionID int64
	IsApplied int64
	Tstamp    sql.NullTime
}

type Item struct {
	ID       int64
	Name     sql.NullString
	Sku      sql.NullString
	Category sql.NullString
}

type Permission struct {
	ID            int64
	Viewtelemetry sql.NullBool
	Viewitems     sql.NullBool
	Manageitems   sql.NullBool
	Preparetags   sql.NullBool
	Manageusers   sql.NullBool
	Lastupdated   sql.NullTime
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}

type Tag struct {
	ID       int64
	Uid      sql.NullString
	Item     sql.NullInt64
	Quantity sql.NullInt64
	Tagtype  sql.NullString
}

type Transaction struct {
	ID                   int64
	Tag                  sql.NullInt64
	Item                 sql.NullInt64
	Quantitychanged      sql.NullInt64
	Newquantity          sql.NullInt64
	Transactiondirection sql.NullString
	Source               sql.NullString
	Timestamp            sql.NullTime
}

type User struct {
	ID             int64
	Username       sql.NullString
	Passworddigest sql.NullString
	Permissions    sql.NullInt64
}
