FROM golang:1.23.0-alpine

RUN apk add --no-cache gcc musl-dev

WORKDIR /app

ENV CGO_ENABLED=1

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN go mod download

COPY . ./

CMD ["air", "-c", ".air.toml"]
